{{- $nm := include "cmak.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cmak.name" . }}
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cmak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cmak.labels" . | nindent 8 }}
    spec:
      {{- if or .Values.ui.consumerProperties .Values.ui.consumerPropertiesSsl }}
      volumes:
        {{- if .Values.ui.consumerProperties }}
        - name: {{ $nm }}-consumer-properties
          configMap:
            name: {{ $nm }}-consumer-properties
        {{- end -}}
        {{ if .Values.ui.consumerPropertiesSsl }}
        - name: {{ $nm }}-ssl
          secret:
            secretName: {{ include "cmak.name" . }}-ssl
        {{- end -}}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{  toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{  toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{  toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: zk
          image: "{{ .Values.zk.image.repository }}:{{ .Values.zk.image.tag }}"
          imagePullPolicy: "{{ .Values.zk.image.pullPolicy }}"
          ports:
          - name: zk
            containerPort: 2181
            protocol: TCP
          env:
          - name: ZOO_SERVERS
            value: "server.1={{ include "cmak.name" . }}.{{ .Release.Namespace }}:2888:3888;2181"
          - name: ZOO_4LW_COMMANDS_WHITELIST
            value: "ruok,stat"
          livenessProbe:
            exec:
              command: ['sh', '-c', '[ "$(echo ruok | nc 127.0.0.1 2181)" = "imok" ]']
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 15
          {{- if or (.Values.zk.resources.limits | empty | not) (.Values.zk.resources.requests | empty | not) }}
          resources:
            {{- with .Values.zk.resources.requests }}
            requests: {{ . | toYaml | nindent 14 }}
            {{- end }}
            {{- with .Values.zk.resources.limits }}
            limits: {{ . | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: "{{ .Values.ui.image.pullPolicy }}"
          ports:
          - name: http
            containerPort: {{ .Values.ui.port }}
            protocol: TCP
          args:
          - "-Dcmak.zkhosts=127.0.0.1:2181"
          - "-Dhttp.port={{ .Values.ui.port }}"
          {{- range .Values.ui.extraArgs }}
          - {{ . | quote }}
          {{- end }}
          env:
          {{- if .Values.ui.consumerProperties }}
          - name: CONSUMER_PROPERTIES_FILE
            value:  /conf/consumer.properties
          {{- end }}
          {{- with .Values.ui.extraEnv -}}
            {{  toYaml . | nindent 10 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ include "cmak.healthUi" . }}
              port: http
            failureThreshold: 7
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: {{ include "cmak.healthUi" . }}
              port: http
            failureThreshold: 7
            initialDelaySeconds: 45
            timeoutSeconds: 15
            periodSeconds: 30
          {{- if or .Values.ui.consumerProperties .Values.ui.consumerPropertiesSsl }}
          volumeMounts:
          {{- if .Values.ui.consumerProperties }}
            - name: {{ $nm }}-consumer-properties
              mountPath: /conf/consumer.properties
              subPath: consumer.properties
          {{- end -}}
          {{ if .Values.ui.consumerPropertiesSsl }}
            - name: {{ $nm }}-ssl
              mountPath: "/conf/ssl"
          {{- end -}}
          {{- end }}
          {{- if or (.Values.ui.resources.limits | empty | not) (.Values.ui.resources.requests | empty | not) }}
          resources:
            {{- with .Values.ui.resources.requests }}
            requests: {{ . | toYaml | nindent 14 }}
            {{- end }}
            {{- with .Values.ui.resources.limits }}
            limits: {{ . | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
